# 模块路径配置
# 格式: 模块名=相对路径或绝对路径
# 支持 ${projectDir} 变量

base=../AndroidComponentProject/base
router=../AndroidComponentProject/router
network=../AndroidComponentProject/network
login=../AndroidComponentProject/login
home=../AndroidComponentProject/home
user=../AndroidComponentProject/user
reactnative=../AndroidComponentProject/reactnative
logger=../AndroidComponentProject/logger
websdk=../AndroidComponentProject/websdk
